import 'dart:ui';
import 'package:flutter/material.dart';

class model{
  static List<Color> colorlist=[
    Colors.redAccent,
    Colors.red,
    Colors.redAccent.shade100,
    Colors.greenAccent,
    Colors.green,
    Colors.greenAccent.shade100,
    Colors.yellowAccent,
    Colors.yellowAccent.shade100,
    Colors.limeAccent,
    Colors.limeAccent.shade100,
    Colors.purpleAccent,
    Colors.purpleAccent.shade100,
    Colors.purpleAccent.shade200,
    Colors.orangeAccent,
    Colors.orangeAccent.shade100,
    Colors.orangeAccent.shade200,
    Colors.grey,
    Colors.grey.shade100,
    Colors.grey.shade200,
    Colors.brown,
    Colors.brown.shade100,
    Colors.brown.shade200,
    Colors.indigoAccent,
    Colors.indigoAccent.shade100,
    Colors.indigoAccent.shade200,
    Colors.lightBlue,
    Colors.lightBlue.shade100,
    Colors.lightBlue.shade200,
    Colors.tealAccent,
    Colors.tealAccent.shade100,
    Colors.tealAccent.shade200,
    Colors.deepOrange,
    Colors.deepOrange.shade100,
    Colors.deepOrange.shade200,
    Colors.yellow,
    Colors.yellow.shade100,
    Colors.yellow.shade200,
    Colors.green.shade100,
    Colors.green.shade200,
    Colors.teal,
    Colors.teal.shade100,
    Colors.teal.shade200,
    Colors.purple,
    Colors.purple.shade100,
    Colors.purple.shade200,
    Colors.deepPurple,
    Colors.deepPurple.shade100,
    Colors.deepPurple.shade200,
    Colors.lime,
    Colors.lime.shade100,
    Colors.lime.shade200,
    Colors.lightBlue,
    Colors.lightBlue.shade100,
    Colors.lightBlue.shade200,
    Colors.lightGreen,
    Colors.lightGreen.shade100,
    Colors.lightGreen.shade200,
    Colors.lightBlue,
    Colors.lightBlue.shade100,
    Colors.lightBlue.shade200,
    Colors.black,
    Colors.black38,
    Colors.black12,
    Colors.black26,
    Colors.white70,
    Colors.white70,
    Colors.white70,


  ];
}